# Generated by Django 5.1.4 on 2024-12-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='periodo_inscripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
