# Generated by Django 5.1.4 on 2024-12-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_curso_periodo_inscripcion_curso_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='periodo_inscripcion',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='profesor',
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_fin_inscripcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_inicio_inscripcion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
