# Generated by Django 5.1.4 on 2024-12-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0005_profesor_alter_curso_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
